### ISSUE TITLE
Determine method of using latest + override for versions of packages

### ISSUE THREAD

**Issue by echohack** [echohack/deltron#1]
Currently we are hardcoding the values for Chef Server, Automate, and so on. This issue is to help us determine a method for which we can use latest versions of the packages and if necessary, allow the user to override those versions in the `variables.tf` file.

More than likely we'll end up using some combination of chef-zero + the [chef-ingredient](https://github.com/chef-cookbooks/chef-ingredient) cookbook in order to accomplish this, but we should look at other potentially simpler methods as well.

**Comment by andy-dufour** [comment]
The other issue with packages is multi-platform support. We probably only need to worry about EL and Ubuntu, so we could do a poor mans platform detection and have it all in bash. We can get the latest version of products using omnitruck's api, e.g. for Chef server: http://omnitruck.chef.io/stable/chef-server/download?p=el&pv=7&m=x86_64&v=latest

I'm looking at the bash scripts we're writing in this and starting to feel that perhaps using chef zero to build the Chef Server with Chef Vault, then bootstrapping itself and the other nodes to the chef server could be the way to go. We gain chef-ingredient which gives us some sugar for the things we'd have to do a bit of bash scripting around. 

This seems like a bit more complexity then it's worth until I start thinking about the fact we need to handle future upgrades and configuration on long running machines without rebuilding the stack. We can probably discuss further early next week in slack or a sync.

**Comment by echohack** [comment]
We've solved this!
