### ISSUE TITLE
Update AWS tagging to comply with Chef standards

### ISSUE THREAD

**Issue by andy-dufour** [echohack/deltron#4]
There's an internal wiki link i'll dig up somewhere.. leaving this here so we don't forget.

**Comment by echohack** [comment]
In any case, we should really externalize and variabilize these tags as part of this work.

We should share a recommended tagging system so other enterprises who implement tf_chef_automate have a good way of tracking their infra as well.

**Comment by echohack** [comment]
I'd say this is done.
